version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:current
    resource_class: small

jobs:
  build:
    executor: base
    steps:
      - checkout
      - check-processes
      - run: |
          sleep 10
          exit 0

commands:
  check-processes:
    steps:
      - run:
          name: Profile CPU and memory every 2s (background)
          command: |
            while true; do
              sleep 2
              printf "\n\n$(date)\n"
              top -b -c -n 1
              echo "======"
            done
          background: true
